/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Strat, StratInterface } from "../Strat";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_yVault",
        type: "address",
      },
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_vault",
        type: "address",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Strat__factory {
  static readonly abi = _abi;
  static createInterface(): StratInterface {
    return new utils.Interface(_abi) as StratInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Strat {
    return new Contract(address, _abi, signerOrProvider) as Strat;
  }
}
