[default]
src = 'src'
out = '_foundry-artifacts'
libs = ['node_modules']
remappings = ['ds-test/=foundry-lib/ds-test/src/']

# See more config options https://github.com/gakonst/foundry/tree/master/config